Repository anomic30/Storz, pull requests merged in 2022-10, with the labels that each got.

#24 feat: added socials
  client/src/assets/icons/github.svg
  client/src/pages/landing/Landing.css
  client/src/pages/landing/Landing.jsx
Labels: hacktoberfest-accepted, hacktoberfest

#25 fix: file names not wrapping
  client/src/pages/home/Home.css
Labels: hacktoberfest-accepted, hacktoberfest

#26 bug(hover): Fix hover in landing page
  client/src/pages/landing/Landing.jsx
Labels: hacktoberfest-accepted, hacktoberfest

#29 feat: date formatter
  client/src/components/file-desc/Desc.jsx
  client/src/pages/myFiles/MyFiles.jsx
  client/src/utils/formatDates.js
Labels: enhancement, hacktoberfest-accepted, hacktoberfest

#34 Fix: Horizontal Scrolling in Landing page
  client/src/pages/landing/Landing.css
Labels: bug, hacktoberfest

#40 Fix for responsiveness and basic accessibility of file list page, while adding cross-env.
  client/package-lock.json
  client/package.json
  client/src/pages/myFiles/MyFiles.css
  client/src/pages/myFiles/MyFiles.jsx
Labels: bug, hacktoberfest

#42 Updated Readme using as a beginner
  client/README.md
Labels: good first issue, hacktoberfest-accepted, hacktoberfest

#41 Fix margin in File page for mobile devices
  client/src/components/file-desc/Desc.css
Labels: enhancement, hacktoberfest-accepted, hacktoberfest

#32 Update Navbar.jsx
  client/src/components/navbar/Navbar.jsx
Labels: bug, hacktoberfest

#46 Added rate limiter to server
  server/index.js
  server/middlewares/rateLimiter.js
  server/package-lock.json
  server/package.json
Labels: enhancement, hacktoberfest-accepted, hacktoberfest

#39 Fix sign-in and log-in for better UX
  client/src/pages/signin/Signin.css
  client/src/pages/signin/Signin.jsx
Labels: enhancement, good first issue, hacktoberfest-accepted, hacktoberfest

#52 Added Styleguide
  STYLEGUIDE.md
Labels: documentation, hacktoberfest-accepted, hacktoberfest

#63 Aditya dev
  STYLEGUIDE.md
Labels: documentation, hacktoberfest-accepted, hacktoberfest

#68 Fix/some error fixes
  client/src/components/file-desc/Desc.css
  client/src/components/navbar/Navbar.css
  client/src/index.css
  client/src/pages/error/Error.css
  client/src/pages/home/Home.css
  client/src/pages/landing/Landing.css
  client/src/pages/myFiles/MyFiles.css
Labels: hacktoberfest-accepted, hacktoberfest

#74 refactor(download): create function with duplicated code
  server/routes/download.js
Labels: enhancement, hacktoberfest-accepted, hacktoberfest

#59 Added scroll back to top button
  client/src/App.js
  client/src/pages/landing/Landing.css
  client/src/pages/landing/Landing.jsx
  package-lock.json
  package.json
Labels: enhancement, hacktoberfest

#78 docs: added colors in styleguide
  STYLEGUIDE.md
Labels: documentation, hacktoberfest-accepted, hacktoberfest

#64 Enhance file section when file name is too big
  client/src/components/file-desc/Desc.css
  client/src/pages/myFiles/MyFiles.css
Labels: bug, hacktoberfest-accepted, hacktoberfest

#80 added scroll to top to improve UX
  client/src/pages/landing/Landing.css
  client/src/pages/landing/Landing.jsx
Labels: enhancement, hacktoberfest-accepted, hacktoberfest

#83 added new icon and styles to the scroll to top button
  client/src/assets/icons/arrowup.svg
  client/src/pages/landing/Landing.css
  client/src/pages/landing/Landing.jsx
Labels: enhancement, hacktoberfest-accepted, hacktoberfest

#84 added responsiveness to the scroll to top button for both tablet and mobile
  client/src/pages/landing/Landing.css
Labels: enhancement, hacktoberfest-accepted, hacktoberfest

#86 feat: landing page 3d globe
  client/package-lock.json
  client/package.json
  client/src/assets/datasets/ne_110m_admin_0_countries.json
  client/src/components/globe/Globe.jsx
  client/src/pages/landing/Landing.jsx
Labels: enhancement, hacktoberfest-accepted, hacktoberfest

#89 Aditya devv
  client/src/index.css
  client/src/pages/landing/Landing.css
Labels: enhancement, hacktoberfest-accepted

#91 added default node env
  server/.env.example
Labels: good first issue, hacktoberfest-accepted, hacktoberfest

#92 Unselectable images
  client/src/index.css
Labels: enhancement, good first issue, hacktoberfest-accepted

#93 updated guidelines for PR
  CONTRIBUTING.md
Labels: documentation, hacktoberfest-accepted, hacktoberfest

#44 Pagignation added for my files page
  client/package-lock.json
  client/package.json
  client/src/pages/myFiles/MyFiles.css
  client/src/pages/myFiles/MyFiles.jsx
Labels: enhancement, hacktoberfest

#97 fix: removed outlines appearing while clicking on pagination buttons
  client/src/pages/myFiles/MyFiles.css
Labels: bug, hacktoberfest-accepted, hacktoberfest

#98 docs: updated guidelines for node and npm version
  CONTRIBUTING.md
  README.md
  client/src/pages/myFiles/MyFiles.css
Labels: documentation, hacktoberfest-accepted, hacktoberfest

#99 pagination issue fixed
  client/src/pages/myFiles/MyFiles.jsx
  server/package-lock.json
Labels: bug, hacktoberfest-accepted, hacktoberfest

#100 enhanced: left and right arrow for pagination
  client/src/pages/myFiles/MyFiles.css
  client/src/pages/myFiles/MyFiles.jsx
Labels: enhancement, good first issue, hacktoberfest-accepted

#102 Fix cors error
  server/index.js
Labels: bug, hacktoberfest-accepted, hacktoberfest

#106 Fix: Issue-104 Files with same name
  client/src/components/modal/Modal.css
  client/src/components/modal/Modal.jsx
  client/src/pages/home/Home.css
  client/src/pages/home/Home.jsx
  server/routes/upload.js
Labels: bug, hacktoberfest-accepted

#107 Added Filterning and sorting feature for files
  client/src/index.css
  client/src/pages/landing/Landing.css
  client/src/pages/myFiles/MyFiles.css
  client/src/pages/myFiles/MyFiles.jsx
  server/routes/user.js
Labels: enhancement, hacktoberfest-accepted

#108 fix: breaking CSS in file desc component
  client/src/index.css
  client/src/pages/landing/Landing.css
Labels: bug, hacktoberfest-accepted

#109 fix: landing page 3D globe performance
  client/src/components/globe/Globe.jsx
Labels: bug, hacktoberfest-accepted

#110 feat: improve view and control of landing page globe
  client/src/components/globe/Globe.jsx
Labels: enhancement, hacktoberfest-accepted

#111 fix: file not uploading
  client/src/pages/home/Home.jsx
  server/routes/user.js
Labels: bug

#114 enhanced : upload button margin and cursor pointer to cross icon
  client/src/pages/home/Home.css
Labels: enhancement, good first issue, hacktoberfest-accepted

#115 removed tooltip arrows
  client/src/components/file-desc/Desc.jsx
Labels: enhancement, hacktoberfest-accepted
